### ISSUE TITLE
Please correct npm maintainers configuration.

### ISSUE THREAD

**Issue by GermanBluefox** [Newan/ioBroker.yahoo-stock-market#1]
## ioBroker adapter checker for npm access

Access right check for adapter yahoo-stock-market returned the following issue:

Bluefox was not found in the collaborators on NPM!.
Please execute in adapter directory: "npm owner add bluefox iobroker.yahoo-stock-market"

Current maintainers are 
    realnewan <info@newan.de>

Please fix the above error as soon as possible.
All adapters listed at ioBroker repositories must have 'bluefox' added as maintainer.

Future version updates at the repositories will be suspended until this problem is fixed.

**Comment by Newan** [comment]
@GermanBluefox  Failed to update package: "409 Conflict - PUT https://registry.npmjs.org/iobroker.webuntis/-rev/7-8bfa6d2d7288d2acf1fb17a409811d66 - User already has a pending invite"

**Comment by mcm1957** [comment]
should be fixed:
C:\Users\Martin>npm owner list iobroker.yahoo-stock-market
bluefox <dogafox@gmail.com>
realnewan <info@newan.de>
