### ISSUE TITLE
Price not updating: Error: Could not find window.YAHOO.context.

### ISSUE THREAD

**Issue by moobid** [Newan/ioBroker.yahoo-stock-market#11]
**Describe the bug**  
Getting stock information does not work. The price in the iobroker object does not update.
In the logs is an error that indicates an yahoo-API-Endpoint change.

**To Reproduce**  
In the instance settings have "BTC-USD" symbol active (or some other).
After a minute the error in the log occurs.

**Expected behavior**  
The iobroker object should update and no error should occur

**Screenshots & Logfiles**  
![image](https://github.com/Newan/ioBroker.yahoo-stock-market/assets/5289345/275309dd-0cae-413a-8071-9f0ab2544fe2)

repo:Newan/ioBroker.yahoo-stock-market 2024-05-13 15:04:41.937	error	Error: Could not find window.YAHOO.context. This is usually caused by temporary issues on Yahoo's servers that tend to resolve themselves; however, if the error persists for more than 12 hours, Yahoo's API may have changed, and you can help by reporting the issue. Thanks :)

**Versions:**  
 - Adapter version: 0.05
 - JS-Controller version: 5.0.17
 - Node version: v18.17.1

**Comment by Newan** [comment]
please check 0.0.6

**Comment by moobid** [comment]
It is not available yet in iobroker. I dont know how to "activate" getting the update faster.
But I will check this when it is available

**Comment by moobid** [comment]
IoBroker now supplies the 0.0.6 version and this version fixed the issue. The price gets updated and the log messages are not printed
