### ISSUE TITLE
Error: Invalid Cookie

### ISSUE THREAD

**Issue by backfisch88** [Newan/ioBroker.yahoo-stock-market#5]
<html>
<body>
<div class="MuiGrid-root MuiGrid-container MuiGrid-item css-n6nfem" style="box-sizing: border-box; display: flex; flex-flow: row wrap; width: 1508px; margin: 0px; -webkit-box-align: center; align-items: center; max-width: none; color: rgb(255, 255, 255); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, &quot;Courier New&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span aria-label="Fehler anzeigen" class="MuiBadge-root css-1rzb3uu" style="box-sizing: inherit; position: relative; display: inline-flex; vertical-align: middle; flex-shrink: 0;"><span class="MuiBadge-badge iob371 iob372 MuiBadge-standard MuiBadge-invisible MuiBadge-anchorOriginTopRight MuiBadge-anchorOriginTopRightRectangular MuiBadge-overlapRectangular MuiBadge-colorError css-136xit8" style="box-sizing: border-box; display: flex; flex-flow: row wrap; -webkit-box-pack: center; place-content: center; -webkit-box-align: center; align-items: center; position: absolute; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; font-size: 0.75rem; min-width: 20px; line-height: 1; padding: 0px 6px; height: 20px; border-radius: 10px; z-index: 1; transition: transform 195ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; background-color: rgb(244, 67, 54); color: rgb(255, 255, 255); top: 10px; right: 10px; transform: scale(0) translate(50%, -50%); transform-origin: 100% 0%;">0</span></span><span aria-label="Fehler und Warnungen anzeigen" class="MuiBadge-root css-1rzb3uu" style="box-sizing: inherit; position: relative; display: inline-flex; vertical-align: middle; flex-shrink: 0;"><button class="MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-6ci2yv" tabindex="0" type="button" control-id="ControlID-370" style="box-sizing: border-box; display: inline-flex; -webkit-box-align: center; align-items: center; -webkit-box-pack: center; justify-content: center; position: relative; -webkit-tap-highlight-color: transparent; background-color: transparent; outline: 0px; border: 0px; margin: 0px; cursor: pointer; user-select: none; vertical-align: middle; appearance: none; text-decoration: none; text-align: center; flex: 0 0 auto; border-radius: 50%; overflow: visible; color: rgb(255, 255, 255); transition: background-color 150ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; padding: 12px; font-size: 1.75rem;"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="WarningIcon"><path d="M1 21h22L12 2 1 21zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z"></path></svg><span class="MuiTouchRipple-root css-w0pj6f" style="box-sizing: inherit; overflow: hidden; pointer-events: none; position: absolute; z-index: 0; inset: 0px; border-radius: inherit;"></span></button><span class="MuiBadge-badge iob371 iob373 MuiBadge-standard MuiBadge-anchorOriginTopRight MuiBadge-anchorOriginTopRightRectangular MuiBadge-overlapRectangular css-1o4n2ye" style="box-sizing: border-box; display: flex; flex-flow: row wrap; -webkit-box-pack: center; place-content: center; -webkit-box-align: center; align-items: center; position: absolute; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; font-size: 0.75rem; min-width: 20px; line-height: 1; padding: 0px 6px; height: 20px; border-radius: 10px; z-index: 1; transition: transform 225ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; top: 10px; right: 10px; transform: scale(1) translate(50%, -50%); transform-origin: 100% 0%; background-color: rgb(255, 193, 7);">2</span></span><div class="iob360" style="box-sizing: inherit; flex-grow: 1;"></div><div style="box-sizing: inherit;"><button class="MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium css-1vannuk" tabindex="0" type="button" control-id="ControlID-371" style="box-sizing: border-box; display: inline-flex; -webkit-box-align: center; align-items: center; -webkit-box-pack: center; justify-content: center; position: relative; -webkit-tap-highlight-color: transparent; outline: 0px; border: 0px; margin: 0px; cursor: pointer; user-select: none; vertical-align: middle; appearance: none; text-decoration: none; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; font-size: 0.875rem; line-height: 1.75; letter-spacing: 0.02857em; text-transform: uppercase; min-width: 64px; padding: 6px 16px; border-radius: 4px; transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, border-color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; color: rgba(0, 0, 0, 0.87); background-color: rgb(77, 171, 245); box-shadow: rgba(0, 0, 0, 0.2) 0px 3px 1px -2px, rgba(0, 0, 0, 0.14) 0px 2px 2px 0px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;"><span class="MuiButton-startIcon MuiButton-iconSizeMedium css-6xugel" style="box-sizing: inherit; display: inherit; margin-right: 8px; margin-left: -4px;"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="SaveAltIcon"><path d="M19 12v7H5v-7H3v7c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-7h-2zm-6 .67 2.59-2.58L17 11.5l-5 5-5-5 1.41-1.41L11 12.67V3h2z"></path></svg></span>LOG HERUNTERLADEN<span class="MuiTouchRipple-root css-w0pj6f" style="box-sizing: inherit; overflow: hidden; pointer-events: none; position: absolute; z-index: 0; inset: 0px; border-radius: inherit;"></span></button></div><div class="iob360" style="box-sizing: inherit; flex-grow: 1;"></div><p class="MuiTypography-root MuiTypography-body2 iob361 css-68o8xu" title="" style="box-sizing: inherit; margin: 0px 1rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; font-size: 0.875rem; line-height: 1.43; letter-spacing: 0.01071em;">Log-Größe:<span> </span><span class="" style="box-sizing: inherit;">141.2 KB</span></p></div><div class="MuiGrid-root MuiGrid-item iob382 css-1wxaqej" style="box-sizing: border-box; margin: 0px; flex-direction: row; height: 1147px; overflow: hidden; max-width: none; color: rgb(255, 255, 255); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, &quot;Courier New&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="MuiTableContainer-root iob338 css-kge0eu" style="box-sizing: inherit; width: 1508px; overflow-x: auto; height: 1147px;">

Quelle | Zeit | error | Nachricht
-- | -- | -- | --
yahoo-stock-market.0 | 2023-07-14 08:42:50.570 | error | Error: Invalid Cookie
yahoo-stock-market.0 | 2023-07-14 08:42:50.570 | error | Error on APi Call for symbol: FRA.F
yahoo-stock-market.0 | 2023-07-14 08:42:50.565 | error | Error: Invalid Cookie
yahoo-stock-market.0 | 2023-07-14 08:42:50.565 | error | Error on APi Call for symbol: PA=F
yahoo-stock-market.0 | 2023-07-14 08:42:50.552 | error | Error: Invalid Cookie
yahoo-stock-market.0 | 2023-07-14 08:42:50.552 | error | Error on APi Call for symbol: AAPL

</div></div>
</body>
</html>

kommt bei jeder Abfrage

**Comment by m4ding** [comment]
Ich habe das gleiche Problem, v 0.0.4

**Comment by Newan** [comment]
bitte letzten commit testen

**Comment by backfisch88** [comment]
So. Gerade erst heim gekommen. Mitm neusten commit gehts. Danke für die schnelle Hilfe 😀
