### ISSUE TITLE
Import/export list of symbols

### ISSUE THREAD

**Issue by JayVee2** [Newan/ioBroker.yahoo-stock-market#8]
Great adapter.
I'd like to use it to watch a larger number of symbols to be imported from excel.
Would be great to have an import/export function for symbols.
Thanks
-J

**Comment by Newan** [comment]
save excel as csv, post csv into the symbol field .... ?

**Comment by JayVee2** [comment]
Vielen Dank für die Rückmeldung.

Einfacher Export hat für mich nicht funktioniert, da die Symbole von Excel (Refinitiv) nicht immer kompatibel mit denen von Yahoo-Finance sind

Der Adapter ist klasse, ich habe lange nach so etwas gesucht. Am Ende habe ich mir die entscheidenden Zeilen in ein eigenes Skript kopiert und an einen Socket gebunden. Damit kann ich die Daten von Excel automatisiert per POST an mein Skript übertragen, dort die fehlenden Werte von Yahoo ergänzen, bzw. Limit Prüfungen durchführen (24/7) und On-demand das Ganze auf demselben Weg wieder zurückliefern.

Dieser Adapter hat mich auf ein paar echt gute Ideen gebracht. Danke.
