### ISSUE TITLE
Error: Invalid Crumb

### ISSUE THREAD

**Issue by Maxtor62** [Newan/ioBroker.yahoo-stock-market#9]
Since today at 06:00 am 

yahoo-stock-market.0 | 2024-04-15 14:18:41.925 | error | Error: Invalid Crumb
-- | -- | -- | --
yahoo-stock-market.0 | 2024-04-15 14:18:41.925 | error | Error on APi Call for symbol: sap.de
yahoo-stock-market.0 | 2024-04-15 14:18:41.920 | error | Error: Invalid Crumb
yahoo-stock-market.0 | 2024-04-15 14:18:41.920 | error | Error on APi Call for symbol: btc-usd
yahoo-stock-market.0 | 2024-04-15 14:18:41.919 | error | Error: Invalid Crumb
yahoo-stock-market.0 | 2024-04-15 14:18:41.919 | error | Error on APi Call for symbol: btc-eur

**Comment by stonemaan** [comment]
same here

**Comment by btckai** [comment]
Same for me ...
